version: 2.1

jobs:
  build_image:
    parameters:
      image_name:
        type: string
        default: myTestImage
    machine: true
    steps:
      - checkout
      - run: docker build -t << parameters.image_name  >> .
      - run: docker info

workflows:
  workflow:
    jobs:
      - build_image:
          image_name: my_test_image_from_workflows