version: 2.1

parameters:
  image-name:
    type: string
    default: "test_image"
  image-tag:
    type: string
    default: "latest"

jobs:
  setup_env:
    machine: true
    description: Setup CircleCi client environment
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            echo "Setup Environment Stage"            
              
  build_container:
    machine: true
    steps:
      - checkout
      - run: whoami
      - run: DOCKER_BUILDKIT=1 docker build -t << pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >> .
      - run: docker info
      - run: docker images
      - run:
          name: Test multiple commands with command
          command: |
            whoami
            ls -li *
            pwd
            uname -a
            docker info
            docker images

  build_container2:
    machine: true
    description: Fan out with build_container job
    steps:
      - checkout
      - run: whoami
      - run: DOCKER_BUILDKIT=1 docker build -t << pipeline.parameters.image-name >>2:<< pipeline.parameters.image-tag >> .
      - run: docker info
      - run: docker images
      - run:
          name: Test multiple commands with command
          command: |
            whoami
            ls -li *
            pwd
            uname -a
            docker info
            docker images
run_container:
  machine: true
  description: Fan in with build_container and build_container2
  steps:
    - run: echo << pipeline.parameters.image-name >>:<<  pipeline.parameters.image-tag  >>
    - run: docker run -it --rm << pipeline.parameters.image-name >>:<<  pipeline.parameters.image-tag  >>


workflows:
  build_and_test:
    jobs:
      - setup_env
      - build_container:
          requires:
            - setup_env
      - build_container2:
          requires:
            - setup_env
      - run_container:
          requires:
            - setup_env
            - build_container
            - build_container2


        
