version: 2.1

parameters:
  image_name:
    type: string
    default: "latest"

jobs:
  build_container:
    machine: true
    steps:
      - checkout
      - run: whoami
      - run: DOCKER_BUILDKIT=1 docker build -t << pipeline.parameters.image-tag >> .
      - run: docker info
      - run: docker images
  run_container:
    steps:
      - run: docker run -it --rm << pipeline.parameters.image-tag >>


workflows:
  workflow:
    jobs:
      - build_container:
      - run_container:
