version: 2.1

parameters:
  image-name:
    type: string
    default: "test_image"
  image-tag:
    type: string
    default: "latest"

jobs:
  build_container:
    machine: true
    steps:
      - checkout
      - run: whoami
      - run: DOCKER_BUILDKIT=1 docker build -t << pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >> .
      - run: docker info
      - run: docker images
  run_container:
    machine: true
    steps:
      - run: echo << pipeline.parameters.image-name >>:<<  pipeline.parameters.image-tag  >>
      - run: docker run -it --rm << pipeline.parameters.image-name >>:<<  pipeline.parameters.image-tag  >>


workflows:
  workflow:
    jobs:
      - build_container
      - run_container:
        requires:
          - build_container


        
