version: 2.1

parameters:
  image-name:
    type: string
    default: "test_image"
  image-tag:
    type: string
    default: "latest"

jobs:
  setup_env:
    machine: true
    description: Setup CircleCi client environment
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            echo "Setup Environment Stage"            
              
  build_container:
    machine: true
    steps:
      - checkout
      - run: whoami
      - run: DOCKER_BUILDKIT=1 docker build -t << pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >> .
      - run: docker info
      - run: docker images
      - run:
          name: Archive Docker image
          command: docker save -o image.tar << pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>
      - run:
          name: Test multiple commands with command
          command: |
            whoami
            ls -li *
            pwd
            uname -a
            docker info
            docker images
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  build_container2:
    machine: true
    description: Fan out with build_container job
    steps:
      - checkout
      - run: DOCKER_BUILDKIT=1 docker build -t << pipeline.parameters.image-name >>2:<< pipeline.parameters.image-tag >> .
      - run: docker info
      - run: docker images
      - run:
          name: Archive Docker image
          command: docker save -o image2.tar << pipeline.parameters.image-name >>2:<< pipeline.parameters.image-tag >>
      - persist_to_workspace:
          root: .
          paths:
            - ./image2.tar

  test_containers:
    machine: true
    description: Fan in from build_container and build_container2. Run containers python application and unit-test math operations
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Load archived Docker image2
          command: docker load -i /tmp/workspace/image2.tar
      - run: docker images
      - run: 
          name: Testing First Container
          command: docker run -it --rm << pipeline.parameters.image-name >>:<<  pipeline.parameters.image-tag  >>
      - run:
          name: Testing Second Container
          command: docker run -it --rm << pipeline.parameters.image-name >>2:<<  pipeline.parameters.image-tag  >>

  push_image:
    description: Pushing tar images to Docker Hub registry using CircleCi Context
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Pull image.tar from build_image job's workspace, unpack and push to remote Docker hub, save image.tar to artifact db
          command: |
            docker load -i /tmp/workspace/image.tar
            docker images
            docker tag << pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >> $DOCKER_USERNAME/circleci/circleci_image:v1.0
            docker images
            # docker logout
            # docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD 
            # docker push $DOCKER_USERNAME/circleci/circleci_image:v1.0
            # docker image ls -a $DOCKER_USERNAME/circleci
      - store_artifacts:
          path: /tmp/workspace/image.tar

workflows:
  build_and_test:
    jobs:
      - setup_env
      - build_container:
          requires:
            - setup_env
      # - build_container2:
      #     requires:
      #       - setup_env
      # - test_containers:
      #     requires:
      #       - build_container
      #       - build_container2
      # - push_image:
      #     context:
      #       docker
      #     requires:
      #       - build_container