version: 2.1

parameters:
  image-name:
    type: string
    default: "test_image"
  image-tag:
    type: string
    default: "latest"

jobs:
  setup_env:
    machine: true
    description: Setup CircleCi client environment
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: pip install --upgrade pip
      - run:
          command: |
            pip install virtualenv
            virtualenv -p python3 myEnv
            source myEnv/bin/activate
            ls -li
            deactivate
              
  build_container:
    machine: true
    steps:
      - checkout
      - run: whoami
      - run: DOCKER_BUILDKIT=1 docker build -t << pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >> .
      - run: docker info
      - run: docker images
      - run:
          name: Test multiple commands with command
          command: |
            whoami
            ls -li *
            pwd
            uname -a
            docker info
            docker images
  run_container:
    machine: true
    steps:
      - run: echo << pipeline.parameters.image-name >>:<<  pipeline.parameters.image-tag  >>
      - run: docker run -it --rm << pipeline.parameters.image-name >>:<<  pipeline.parameters.image-tag  >>


workflows:
  build_and_test:
    jobs:
      - setup_env
      - build_container:
          requires:
            - setup_env
      - run_container:
          requires:
            - setup_env
            - build_container


        
